/**
 * Catalog section metadata — single source of truth (no React components).
 * Used for route matching, layout nav, and CatalogSectionPage config.
 */
export const catalogChildRouteConfigs = [
  {
    key: "/super-admin/catalog/financial-institutions",
    relativePath: "financial-institutions",
    catalogDataKey: "FinancialInstitutions",
    catalogTitle: "Financial Institutions",
    catalogIcon: "🏦",
    menuIcon: "🏦",
    menuLabel: "Financial Institutions",
    addButtonLabel: "Add Institution",
    paginationItemLabel: "institutions",
    deleteSuccessLabel: "Institution",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/investment-platforms",
    relativePath: "investment-platforms",
    catalogDataKey: "InvestmentPlatforms",
    catalogTitle: "Investment Platforms",
    catalogIcon: "📊",
    menuIcon: "📊",
    menuLabel: "Investment Platforms",
    addButtonLabel: "Add Platform",
    paginationItemLabel: "platforms",
    deleteSuccessLabel: "Platform",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/investment-bonds",
    relativePath: "investment-bonds",
    catalogDataKey: "InvestmentBonds",
    catalogTitle: "Investment Bonds",
    catalogIcon: "🎖️",
    menuIcon: "🎖️",
    menuLabel: "Investment Bonds",
    addButtonLabel: "Add Bond",
    paginationItemLabel: "bonds",
    deleteSuccessLabel: "Bond",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/superannuation-funds", 
    relativePath: "superannuation-funds",
    catalogDataKey: "SuperannuationFunds",
    catalogTitle: "Superannuation Funds",
    catalogIcon: "💰",
    menuIcon: "💰",
    menuLabel: "Superannuation Funds",
    addButtonLabel: "Add Fund",
    paginationItemLabel: "funds",
    deleteSuccessLabel: "Fund",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/account-based-pensions", 
    relativePath: "account-based-pensions",
    catalogDataKey: "AccountBasedPensions",
    catalogTitle: "Account Based Pensions",
    catalogIcon: "📋",
    menuIcon: "📋",
    menuLabel: "Account Based Pensions",
    addButtonLabel: "Add Pension",
    paginationItemLabel: "pensions",
    deleteSuccessLabel: "Pension",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/annuities", 
    relativePath: "annuities",
    catalogDataKey: "Annuities",
    catalogTitle: "Annuities",
    catalogIcon: "💲",
    menuIcon: "💲",
    menuLabel: "Annuities",
    addButtonLabel: "Add Annuity",
    paginationItemLabel: "annuities",
    deleteSuccessLabel: "Annuity",
    defaultType: "Bank",
    showTypeColumn: true,
  },
  {
    key: "/super-admin/catalog/personal-insurances", 
    relativePath: "personal-insurances",
    catalogDataKey: "PersonalInsurances",
    catalogTitle: "Personal Insurances",
    catalogIcon: "🛡️",
    menuIcon: "🛡️",
    menuLabel: "Personal Insurances",
    addButtonLabel: "Add Insurance",
    paginationItemLabel: "insurances",
    deleteSuccessLabel: "Insurance",
    defaultType: "Bank",
    showTypeColumn: true,
  },
];
